import { Injectable, signal } from '@angular/core';

export type Language = 'pt' | 'en';

const STORAGE_KEY = 'erp-suite-language';

const translations: Record<Language, Record<string, string>> = {
  pt: {
    'app.operations': 'Operacoes',
    'app.language': 'Idioma',
    'app.pt': 'PT',
    'app.en': 'EN',
    'nav.dashboard': 'Dashboard',
    'nav.materials': 'Materiais',
    'nav.organization': 'Organizacao',
    'nav.catalog': 'Catalogo',
    'nav.inventory': 'Estoque',
    'nav.partners': 'Parceiros',
    'nav.purchasing': 'Compras',
    'nav.sales': 'Vendas',
    'nav.finance': 'Financeiro',
    'nav.users': 'Usuarios',
    'nav.audit': 'Auditoria',
    'common.search': 'Buscar',
    'common.clear': 'Limpar',
    'common.save': 'Salvar',
    'common.edit': 'Editar',
    'common.cancel': 'Cancelar',
    'common.active': 'Ativo',
    'common.records': 'registros',
    'common.items': 'itens',
    'common.code': 'Codigo',
    'common.description': 'Descricao',
    'common.category': 'Categoria',
    'common.date': 'Data',
    'common.status': 'Status',
    'common.total': 'Total',
    'common.number': 'Numero',
    'common.customer': 'Cliente',
    'common.customers': 'Clientes',
    'common.supplier': 'Fornecedor',
    'common.suppliers': 'Fornecedores',
    'common.partner': 'Parceiro',
    'common.material': 'Material',
    'common.quantity': 'Quantidade',
    'common.type': 'Tipo',
    'common.value': 'Valor',
    'common.email': 'Email',
    'common.password': 'Senha',
    'common.role': 'Perfil',
    'common.name': 'Nome',
    'common.phone': 'Telefone',
    'common.contact': 'Contato',
    'common.document': 'Documento',
    'common.user': 'Usuario',
    'common.system': 'Sistema',
    'common.details': 'Detalhes',
    'common.view': 'Ver',
    'common.method': 'Metodo',
    'common.entity': 'Entidade',
    'common.origin': 'Origem',
    'common.loadingMetrics': 'Carregando indicadores...',
    'shell.logout': 'Sair',
    'auth.loginTitle': 'Entrar no sistema',
    'auth.loginHelp': 'Use o usuario inicial criado pelo seed ou cadastre o primeiro administrador.',
    'auth.loggingIn': 'Entrando...',
    'auth.login': 'Entrar',
    'auth.noAccess': 'Ainda nao tem acesso?',
    'auth.registerUser': 'Cadastrar usuario',
    'auth.newAccess': 'Novo acesso',
    'auth.registerTitle': 'Cadastro de usuario',
    'auth.registerHelp': 'O primeiro usuario vira administrador. Depois disso, novos cadastros entram como operador, salvo quando feitos por admin.',
    'auth.fullName': 'Nome completo',
    'auth.registering': 'Cadastrando...',
    'auth.registerAndLogin': 'Cadastrar e entrar',
    'auth.hasUser': 'Ja tem usuario?',
    'dashboard.overview': 'Visao geral',
    'dashboard.title': 'Dashboard operacional',
    'dashboard.activeMaterials': 'Materiais ativos',
    'dashboard.activeCustomers': 'Clientes ativos',
    'dashboard.activeSuppliers': 'Fornecedores',
    'dashboard.openPurchases': 'Compras abertas',
    'dashboard.openSales': 'Vendas abertas',
    'dashboard.lowStock': 'Estoque baixo',
    'dashboard.inventoryValue': 'Valor em estoque',
    'dashboard.openPayables': 'A pagar aberto',
    'dashboard.openReceivables': 'A receber aberto',
    'dashboard.overdueFinance': 'Financeiro vencido',
    'dashboard.belowMinimum': 'Itens abaixo do minimo',
    'dashboard.noLowStock': 'Nenhum item abaixo do minimo.',
    'materials.eyebrow': 'Cadastro e consulta',
    'materials.title': 'Materiais',
    'materials.searchPlaceholder': 'Buscar por codigo ou descricao',
    'materials.edit': 'Editar material',
    'materials.new': 'Novo material',
    'materials.unit': 'Unidade',
    'materials.preferredSupplier': 'Fornecedor preferencial',
    'materials.noSupplier': 'Sem fornecedor',
    'materials.standardCost': 'Custo padrao',
    'materials.salePrice': 'Preco venda',
    'materials.minimumStock': 'Estoque minimo',
    'materials.saving': 'Salvando...',
    'materials.save': 'Salvar material',
    'materials.query': 'Consulta',
    'materials.balance': 'Saldo',
    'materials.cost': 'Custo',
    'materials.deactivate': 'Inativar',
    'materials.empty': 'Nenhum material encontrado.',
    'organization.eyebrow': 'Estrutura',
    'organization.title': 'Empresas, filiais e centros de custo',
    'organization.company': 'Empresa',
    'organization.branch': 'Filial',
    'organization.companies': 'Empresas',
    'organization.branches': 'Filiais',
    'organization.costCenters': 'Centros de custo',
    'organization.newCompany': 'Nova empresa',
    'organization.editCompany': 'Editar empresa',
    'organization.saveCompany': 'Salvar empresa',
    'organization.newBranch': 'Nova filial',
    'organization.editBranch': 'Editar filial',
    'organization.saveBranch': 'Salvar filial',
    'organization.newCostCenter': 'Novo centro de custo',
    'organization.editCostCenter': 'Editar centro de custo',
    'organization.saveCostCenter': 'Salvar centro de custo',
    'organization.address': 'Endereco',
    'organization.noCompanies': 'Nenhuma empresa encontrada.',
    'organization.noBranches': 'Nenhuma filial encontrada.',
    'organization.noCostCenters': 'Nenhum centro de custo encontrado.',
    'catalog.eyebrow': 'Cadastros base',
    'catalog.title': 'Almoxarifados, unidades, moedas e cotacoes',
    'catalog.displayCurrency': 'Moeda da interface',
    'catalog.warehouses': 'Almoxarifados',
    'catalog.newWarehouse': 'Novo almoxarifado',
    'catalog.editWarehouse': 'Editar almoxarifado',
    'catalog.saveWarehouse': 'Salvar almoxarifado',
    'catalog.location': 'Localizacao',
    'catalog.noBranch': 'Sem filial',
    'catalog.noWarehouses': 'Nenhum almoxarifado encontrado.',
    'catalog.units': 'Unidades de medida',
    'catalog.newUnit': 'Nova unidade',
    'catalog.editUnit': 'Editar unidade',
    'catalog.createUnit': 'Cadastrar unidade',
    'catalog.updateUnit': 'Atualizar unidade',
    'catalog.saveUnit': 'Salvar unidade',
    'catalog.noUnits': 'Nenhuma unidade encontrada.',
    'catalog.currencies': 'Moedas',
    'catalog.newCurrency': 'Nova moeda',
    'catalog.editCurrency': 'Editar moeda',
    'catalog.currencyCode': 'Codigo ISO',
    'catalog.currencySymbol': 'Simbolo',
    'catalog.defaultCurrency': 'Moeda padrao',
    'catalog.saveCurrency': 'Salvar moeda',
    'catalog.default': 'Padrao',
    'catalog.useCurrency': 'Usar',
    'catalog.noCurrencies': 'Nenhuma moeda encontrada.',
    'catalog.exchangeRates': 'Cotacoes',
    'catalog.newExchangeRate': 'Nova cotacao',
    'catalog.editExchangeRate': 'Editar cotacao',
    'catalog.saveExchangeRate': 'Salvar cotacao',
    'catalog.fromCurrency': 'Moeda origem',
    'catalog.toCurrency': 'Moeda destino',
    'catalog.rateDate': 'Data da cotacao',
    'catalog.rate': 'Taxa',
    'catalog.source': 'Fonte',
    'catalog.noExchangeRates': 'Nenhuma cotacao encontrada.',
    'inventory.eyebrow': 'Estoque',
    'inventory.title': 'Saldos e movimentacoes',
    'inventory.newMovement': 'Nova movimentacao',
    'inventory.warehouse': 'Almoxarifado',
    'inventory.unitCost': 'Custo unitario',
    'inventory.reference': 'Referencia',
    'inventory.notes': 'Observacoes',
    'inventory.registerMovement': 'Registrar movimentacao',
    'inventory.currentBalances': 'Saldos atuais',
    'inventory.current': 'Atual',
    'inventory.value': 'Valor',
    'inventory.latestMovements': 'Ultimas movimentacoes',
    'inventory.warehouseShort': 'Almox.',
    'inventory.qtyShort': 'Qtd.',
    'inventory.refShort': 'Ref.',
    'orders.purchasingEyebrow': 'Suprimentos',
    'orders.salesEyebrow': 'Comercial',
    'orders.purchaseTitle': 'Pedidos de compra',
    'orders.salesTitle': 'Pedidos de venda',
    'orders.newOrder': 'Novo pedido',
    'orders.unitCost': 'Custo unitario',
    'orders.unitPrice': 'Preco unitario',
    'orders.warehouseFor': 'Almoxarifado para',
    'orders.receiving': 'recebimento',
    'orders.shipping': 'expedicao',
    'orders.notes': 'Observacoes',
    'orders.create': 'Criar pedido',
    'orders.recent': 'Pedidos recentes',
    'orders.receive': 'Receber',
    'orders.ship': 'Expedir',
    'orders.empty': 'Nenhum pedido encontrado.',
    'partners.eyebrow': 'Cadastros',
    'partners.title': 'Clientes e fornecedores',
    'partners.edit': 'Editar cadastro',
    'partners.new': 'Novo cadastro',
    'partners.taxId': 'CPF/CNPJ',
    'partners.save': 'Salvar cadastro',
    'partners.empty': 'Nenhum cadastro encontrado.',
    'finance.eyebrow': 'Financeiro',
    'finance.title': 'Contas a pagar e receber',
    'finance.active': 'Ativos',
    'finance.open': 'Em aberto',
    'finance.paid': 'Baixados',
    'finance.cancelled': 'Cancelados',
    'finance.refresh': 'Atualizar',
    'finance.openPayables': 'A pagar aberto',
    'finance.overduePayables': 'A pagar vencido',
    'finance.openReceivables': 'A receber aberto',
    'finance.overdueReceivables': 'A receber vencido',
    'finance.paidThisMonth': 'Pago no mes',
    'finance.receivedThisMonth': 'Recebido no mes',
    'finance.netCashFlow': 'Fluxo liquido',
    'finance.newEntry': 'Novo lancamento',
    'finance.payable': 'Conta a pagar',
    'finance.receivable': 'Conta a receber',
    'finance.dueDate': 'Vencimento',
    'finance.createEntry': 'Criar lancamento',
    'finance.schedule': 'Agenda financeira',
    'finance.payables': 'A pagar',
    'finance.receivables': 'A receber',
    'finance.openAmount': 'Valor aberto',
    'finance.overdue': 'Vencido',
    'finance.pay': 'Pagar',
    'finance.receive': 'Receber',
    'finance.empty': 'Nenhum lancamento financeiro encontrado.',
    'finance.noPartner': 'Sem parceiro',
    'finance.manualEntry': 'Lancamento manual',
    'users.eyebrow': 'Seguranca',
    'users.title': 'Usuarios e perfis',
    'users.registered': 'Usuarios cadastrados',
    'users.empty': 'Nenhum usuario encontrado.',
    'audit.eyebrow': 'Seguranca',
    'audit.title': 'Auditoria do sistema',
    'audit.filterPlaceholder': 'Filtrar entidade. Ex: Materials',
    'audit.events': 'Eventos registrados',
    'audit.action': 'Acao',
    'audit.empty': 'Nenhum log encontrado.',
    'status.Open': 'Aberto',
    'status.Draft': 'Rascunho',
    'status.Confirmed': 'Confirmado',
    'status.PartiallyReceived': 'Parcialmente recebido',
    'status.PartiallyShipped': 'Parcialmente expedido',
    'status.Paid': 'Pago',
    'status.Cancelled': 'Cancelado',
    'status.Received': 'Recebido',
    'status.Shipped': 'Expedido',
    'movement.Adjustment': 'Ajuste',
    'movement.Inbound': 'Entrada',
    'movement.Outbound': 'Saida',
    'movement.PurchaseReceipt': 'Recebimento de compra',
    'movement.SalesShipment': 'Expedicao de venda',
    'role.Admin': 'Admin',
    'role.Manager': 'Gerente',
    'role.Buyer': 'Comprador',
    'role.Seller': 'Vendedor',
    'role.Stock': 'Estoque',
    'role.Operator': 'Operador'
  },
  en: {
    'app.operations': 'Operations',
    'app.language': 'Language',
    'app.pt': 'PT',
    'app.en': 'EN',
    'nav.dashboard': 'Dashboard',
    'nav.materials': 'Materials',
    'nav.organization': 'Organization',
    'nav.catalog': 'Catalog',
    'nav.inventory': 'Inventory',
    'nav.partners': 'Partners',
    'nav.purchasing': 'Purchasing',
    'nav.sales': 'Sales',
    'nav.finance': 'Finance',
    'nav.users': 'Users',
    'nav.audit': 'Audit',
    'common.search': 'Search',
    'common.clear': 'Clear',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.cancel': 'Cancel',
    'common.active': 'Active',
    'common.records': 'records',
    'common.items': 'items',
    'common.code': 'Code',
    'common.description': 'Description',
    'common.category': 'Category',
    'common.date': 'Date',
    'common.status': 'Status',
    'common.total': 'Total',
    'common.number': 'Number',
    'common.customer': 'Customer',
    'common.customers': 'Customers',
    'common.supplier': 'Supplier',
    'common.suppliers': 'Suppliers',
    'common.partner': 'Partner',
    'common.material': 'Material',
    'common.quantity': 'Quantity',
    'common.type': 'Type',
    'common.value': 'Amount',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.role': 'Role',
    'common.name': 'Name',
    'common.phone': 'Phone',
    'common.contact': 'Contact',
    'common.document': 'Document',
    'common.user': 'User',
    'common.system': 'System',
    'common.details': 'Details',
    'common.view': 'View',
    'common.method': 'Method',
    'common.entity': 'Entity',
    'common.origin': 'Origin',
    'common.loadingMetrics': 'Loading metrics...',
    'shell.logout': 'Log out',
    'auth.loginTitle': 'Sign in',
    'auth.loginHelp': 'Use the initial user created by the seed or register the first administrator.',
    'auth.loggingIn': 'Signing in...',
    'auth.login': 'Sign in',
    'auth.noAccess': 'Do not have access yet?',
    'auth.registerUser': 'Register user',
    'auth.newAccess': 'New access',
    'auth.registerTitle': 'User registration',
    'auth.registerHelp': 'The first user becomes an administrator. After that, new registrations are operators unless created by an admin.',
    'auth.fullName': 'Full name',
    'auth.registering': 'Registering...',
    'auth.registerAndLogin': 'Register and sign in',
    'auth.hasUser': 'Already have a user?',
    'dashboard.overview': 'Overview',
    'dashboard.title': 'Operations dashboard',
    'dashboard.activeMaterials': 'Active materials',
    'dashboard.activeCustomers': 'Active customers',
    'dashboard.activeSuppliers': 'Suppliers',
    'dashboard.openPurchases': 'Open purchases',
    'dashboard.openSales': 'Open sales',
    'dashboard.lowStock': 'Low stock',
    'dashboard.inventoryValue': 'Inventory value',
    'dashboard.openPayables': 'Open payables',
    'dashboard.openReceivables': 'Open receivables',
    'dashboard.overdueFinance': 'Overdue finance',
    'dashboard.belowMinimum': 'Items below minimum',
    'dashboard.noLowStock': 'No items below minimum.',
    'materials.eyebrow': 'Register and search',
    'materials.title': 'Materials',
    'materials.searchPlaceholder': 'Search by code or description',
    'materials.edit': 'Edit material',
    'materials.new': 'New material',
    'materials.unit': 'Unit',
    'materials.preferredSupplier': 'Preferred supplier',
    'materials.noSupplier': 'No supplier',
    'materials.standardCost': 'Standard cost',
    'materials.salePrice': 'Sale price',
    'materials.minimumStock': 'Minimum stock',
    'materials.saving': 'Saving...',
    'materials.save': 'Save material',
    'materials.query': 'Search',
    'materials.balance': 'Balance',
    'materials.cost': 'Cost',
    'materials.deactivate': 'Deactivate',
    'materials.empty': 'No materials found.',
    'organization.eyebrow': 'Structure',
    'organization.title': 'Companies, branches and cost centers',
    'organization.company': 'Company',
    'organization.branch': 'Branch',
    'organization.companies': 'Companies',
    'organization.branches': 'Branches',
    'organization.costCenters': 'Cost centers',
    'organization.newCompany': 'New company',
    'organization.editCompany': 'Edit company',
    'organization.saveCompany': 'Save company',
    'organization.newBranch': 'New branch',
    'organization.editBranch': 'Edit branch',
    'organization.saveBranch': 'Save branch',
    'organization.newCostCenter': 'New cost center',
    'organization.editCostCenter': 'Edit cost center',
    'organization.saveCostCenter': 'Save cost center',
    'organization.address': 'Address',
    'organization.noCompanies': 'No companies found.',
    'organization.noBranches': 'No branches found.',
    'organization.noCostCenters': 'No cost centers found.',
    'catalog.eyebrow': 'Base records',
    'catalog.title': 'Warehouses, units, currencies and exchange rates',
    'catalog.displayCurrency': 'Interface currency',
    'catalog.warehouses': 'Warehouses',
    'catalog.newWarehouse': 'New warehouse',
    'catalog.editWarehouse': 'Edit warehouse',
    'catalog.saveWarehouse': 'Save warehouse',
    'catalog.location': 'Location',
    'catalog.noBranch': 'No branch',
    'catalog.noWarehouses': 'No warehouses found.',
    'catalog.units': 'Units of measure',
    'catalog.newUnit': 'New unit',
    'catalog.editUnit': 'Edit unit',
    'catalog.createUnit': 'Create unit',
    'catalog.updateUnit': 'Update unit',
    'catalog.saveUnit': 'Save unit',
    'catalog.noUnits': 'No units found.',
    'catalog.currencies': 'Currencies',
    'catalog.newCurrency': 'New currency',
    'catalog.editCurrency': 'Edit currency',
    'catalog.currencyCode': 'ISO code',
    'catalog.currencySymbol': 'Symbol',
    'catalog.defaultCurrency': 'Default currency',
    'catalog.saveCurrency': 'Save currency',
    'catalog.default': 'Default',
    'catalog.useCurrency': 'Use',
    'catalog.noCurrencies': 'No currencies found.',
    'catalog.exchangeRates': 'Exchange rates',
    'catalog.newExchangeRate': 'New exchange rate',
    'catalog.editExchangeRate': 'Edit exchange rate',
    'catalog.saveExchangeRate': 'Save exchange rate',
    'catalog.fromCurrency': 'Source currency',
    'catalog.toCurrency': 'Target currency',
    'catalog.rateDate': 'Rate date',
    'catalog.rate': 'Rate',
    'catalog.source': 'Source',
    'catalog.noExchangeRates': 'No exchange rates found.',
    'inventory.eyebrow': 'Inventory',
    'inventory.title': 'Balances and movements',
    'inventory.newMovement': 'New movement',
    'inventory.warehouse': 'Warehouse',
    'inventory.unitCost': 'Unit cost',
    'inventory.reference': 'Reference',
    'inventory.notes': 'Notes',
    'inventory.registerMovement': 'Register movement',
    'inventory.currentBalances': 'Current balances',
    'inventory.current': 'Current',
    'inventory.value': 'Value',
    'inventory.latestMovements': 'Latest movements',
    'inventory.warehouseShort': 'Whse.',
    'inventory.qtyShort': 'Qty.',
    'inventory.refShort': 'Ref.',
    'orders.purchasingEyebrow': 'Supply',
    'orders.salesEyebrow': 'Commercial',
    'orders.purchaseTitle': 'Purchase orders',
    'orders.salesTitle': 'Sales orders',
    'orders.newOrder': 'New order',
    'orders.unitCost': 'Unit cost',
    'orders.unitPrice': 'Unit price',
    'orders.warehouseFor': 'Warehouse for',
    'orders.receiving': 'receiving',
    'orders.shipping': 'shipping',
    'orders.notes': 'Notes',
    'orders.create': 'Create order',
    'orders.recent': 'Recent orders',
    'orders.receive': 'Receive',
    'orders.ship': 'Ship',
    'orders.empty': 'No orders found.',
    'partners.eyebrow': 'Records',
    'partners.title': 'Customers and suppliers',
    'partners.edit': 'Edit record',
    'partners.new': 'New record',
    'partners.taxId': 'Tax ID',
    'partners.save': 'Save record',
    'partners.empty': 'No records found.',
    'finance.eyebrow': 'Finance',
    'finance.title': 'Payables and receivables',
    'finance.active': 'Active',
    'finance.open': 'Open',
    'finance.paid': 'Settled',
    'finance.cancelled': 'Cancelled',
    'finance.refresh': 'Refresh',
    'finance.openPayables': 'Open payables',
    'finance.overduePayables': 'Overdue payables',
    'finance.openReceivables': 'Open receivables',
    'finance.overdueReceivables': 'Overdue receivables',
    'finance.paidThisMonth': 'Paid this month',
    'finance.receivedThisMonth': 'Received this month',
    'finance.netCashFlow': 'Net cash flow',
    'finance.newEntry': 'New entry',
    'finance.payable': 'Payable',
    'finance.receivable': 'Receivable',
    'finance.dueDate': 'Due date',
    'finance.createEntry': 'Create entry',
    'finance.schedule': 'Finance schedule',
    'finance.payables': 'Payables',
    'finance.receivables': 'Receivables',
    'finance.openAmount': 'Open amount',
    'finance.overdue': 'Overdue',
    'finance.pay': 'Pay',
    'finance.receive': 'Receive',
    'finance.empty': 'No financial entries found.',
    'finance.noPartner': 'No partner',
    'finance.manualEntry': 'Manual entry',
    'users.eyebrow': 'Security',
    'users.title': 'Users and roles',
    'users.registered': 'Registered users',
    'users.empty': 'No users found.',
    'audit.eyebrow': 'Security',
    'audit.title': 'System audit',
    'audit.filterPlaceholder': 'Filter entity. Ex: Materials',
    'audit.events': 'Registered events',
    'audit.action': 'Action',
    'audit.empty': 'No logs found.',
    'status.Open': 'Open',
    'status.Draft': 'Draft',
    'status.Confirmed': 'Confirmed',
    'status.PartiallyReceived': 'Partially received',
    'status.PartiallyShipped': 'Partially shipped',
    'status.Paid': 'Paid',
    'status.Cancelled': 'Cancelled',
    'status.Received': 'Received',
    'status.Shipped': 'Shipped',
    'movement.Adjustment': 'Adjustment',
    'movement.Inbound': 'Inbound',
    'movement.Outbound': 'Outbound',
    'movement.PurchaseReceipt': 'Purchase receipt',
    'movement.SalesShipment': 'Sales shipment',
    'role.Admin': 'Admin',
    'role.Manager': 'Manager',
    'role.Buyer': 'Buyer',
    'role.Seller': 'Seller',
    'role.Stock': 'Stock',
    'role.Operator': 'Operator'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly language = signal<Language>(this.initialLanguage());

  setLanguage(language: Language) {
    this.language.set(language);
    localStorage.setItem(STORAGE_KEY, language);
  }

  t(key: string) {
    return translations[this.language()][key] ?? translations.pt[key] ?? key;
  }

  private initialLanguage(): Language {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === 'en' || stored === 'pt' ? stored : 'pt';
  }
}
